### ISSUE TITLE
Error: Line number (19) greater than maximum line (17)

### ISSUE THREAD

**Issue by plamb** [AtomLinter/linter-elixirc#36] opened 2016-01-07 21:59 UTC
Using linter-elixir 1.1.4 with Atom 3.2 on a phoenix project (1.1) and elixir 1.2 I'm getting this error message when I save a file.

```
Error: Line number (19) greater than maximum line (17)
    at Object.rangeFromLineNumber (/Users/plamb/.atom/packages/linter-elixirc/node_modules/atom-linter/lib/helpers.js:159:11)
    at parseWarning (/Users/plamb/.atom/packages/linter-elixirc/lib/init.coffee:83:24)
    at /Users/plamb/.atom/packages/linter-elixirc/lib/init.coffee:89:25
    at /Users/plamb/.atom/packages/linter-elixirc/lib/init.coffee:89:25
```

**Comment by Arcanemagus** [comment] 2016-01-07 22:01
Do you have an example file that triggers this?

**Comment by plamb** [comment] 2016-01-07 22:04
It's in a pretty good size phoenix project. Let me start one from scratch and see if it happens there too.

**Comment by Arcanemagus** [comment] 2016-01-07 22:05
For reference, this was already reported in #26, but we never got a response from @divmgl.

**Comment by plamb** [comment] 2016-01-07 22:14
It doesn't happen in a brand new, clean phoenix application. I'll try and do some more checking and see if I can see what triggers it.

**Comment by plamb** [comment] 2016-01-07 22:31
I did clean up all the warnings in the project and now the error message is not coming up anymore.

**Comment by Arcanemagus** [comment] 2016-01-07 23:45
The error is being caused by a call to `helpers.rangeFromLineNumber()` with a line that is after the last line of the file, so if all the messages are cleared up nothing will be calling that and thus it can't be triggered.

What I _suspect_ is going on here is either `elixerc` is giving us back an invalid line, or some part of it's process is modifying the file so what it sees is not the same as what we passed it. Without a file/project to test on though there is no way to know what is going on :frowning:.

**Comment by remiq** [comment] 2016-01-08 15:13
Maybe it is an issue with Elixir's macros? Or Phoenix's html templates? I will check it.

**Comment by remiq** [comment] 2016-01-09 02:25
Steps to trigger this error:
1. Edit long file and make syntax error. Save. Linter shows normal error.
2. Change editor tab into another, shorter file. Save. Linter will show this error.

Why?
We are compiling whole project and returning multiple errors in many files. Since `helpers.rangeFromLineNumber` uses current buffer (which may not be faulty file), we are trying to find error range in incorrect file.

How to fix it?
Since result of rangeFromLineNumber is not very important, we can replace it with constant when faulty file != current file.

I'll fix it tomorrow, unless somebody will be quicker.

**Comment by Arcanemagus** [comment] 2016-01-09 07:46
[linter](https://github.com/atom-community/linter) is only designed to handle providers that return results for the currently active file, if the actual linting program (`elixrc`) is returning results for more than one file you'll need to filter out the files that are not the current file (before generating the range).

If you really want to keep the multi-file error messages you might think about building a [build provider](https://github.com/noseglid/atom-build/blob/v0.52.0/create-provider.md) as that uses most of the same infrastructure, but is meant to handle project level (multi-file) checkers.

**Comment by steelbrain** [comment] 2016-01-09 07:49
Just a side note that linter supports both file and project scoped providers. If we try to set messages on a whole project from a file-scoped project, that messes things up.

Just in case https://github.com/atom-community/linter/wiki/Linter-API

**Comment by divmgl** [comment] 2016-01-11 22:40
Also receiving this problem.

```
Error: Line number (6) greater than maximum line (3)
    at Object.rangeFromLineNumber (C:\Users\dexter.miguel\.atom\packages\linter-elixirc\node_modules\atom-linter\lib\helpers.js:158:11)
    at parseError (file:///C:/Users/dexter.miguel/.atom/packages/linter-elixirc/lib/init.coffee:69:24)
    at file:///C:/Users/dexter.miguel/.atom/packages/linter-elixirc/lib/init.coffee:88:23
    at file:///C:/Users/dexter.miguel/.atom/packages/linter-elixirc/lib/init.coffee:88:23
    at process._tickCallback (node.js:368:9)
```

Here's what makes it crash.

```
defprotocol Dangerous do
  def attack(weapon, defender)
end
```

**Comment by stocks29** [comment] 2016-01-17 19:33
I can confirm I'm also seeing this error as well. My experience seems to match the description above.

**Comment by Arcanemagus** [comment] 2016-01-21 18:29
Looking into this now (after I get an Elixer environment set up...).

Thanks for the example files @divmgl!

**Comment by Arcanemagus** [comment] 2016-01-21 21:19
Well I have no idea how this was working for anyone... the regex works properly on the _full_ output of the command, but is currently being fed a single line at a time which it fails to match on :confused:.

**Comment by Arcanemagus** [comment] 2016-01-21 21:58
Can anyone chime in as to what their output of the following looks like? What I am seeing with the latest available versions of `elixirc` could never have worked, so something must have changed in the output:
Windows:
* `elixirc --ignore-module-conflict --app mix --app ex_unit -o %TEMP% .\ninja.ex`
Linux:
* `elixirc --ignore-module-conflict --app mix --app ex_unit -o /tmp ./ninja.ex`

Here is what I am seeing:
Windows:
![image](https://cloud.githubusercontent.com/assets/427137/12495853/ef529328-c046-11e5-973a-027e2571a8f3.png)
Ubuntu:
![image](https://cloud.githubusercontent.com/assets/427137/12495863/0525191e-c047-11e5-95af-291546691e23.png)

**Comment by divmgl** [comment] 2016-01-23 00:10
Well technically it isn't valid code; maybe we can capture this problem and turn it into a linting problem rather than have it pop up as an error with the plugin.

**Comment by Arcanemagus** [comment] 2016-01-26 17:34
Can I get some testing on #45? I _think_ this fixes this issue, as the output of `elixirc` seems to have changed quite a bit. That also changes the scope to `project` which may fix the issue as @remiq suggested earlier.

**Comment by divmgl** [comment] 2016-01-26 18:56
I'll test it tonight @Arcanemagus appreciate your proactiveness with this!

**Comment by Arcanemagus** [comment] 2016-03-23 07:23
This _should_ be fixed in v1.1.6. Please re-open or file a new issue if you are still seeing this.

**Comment by Cifer-Y** [comment] 2016-03-23 08:01
@Arcanemagus I still can see this issue.

to prevent other packages' interference, I disabled all my atom's community packages, except three:
1. language-elixir, 2.linter, 3.linter-elixirc

Then go to any elixir file I wrote and press cmd-s to save, the error poped up

**Comment by Arcanemagus** [comment] 2016-03-23 16:31
@Cifer-Y are you able to share any of those files? I don't see it on 4 different systems with the simple files from [this comment](https://github.com/AtomLinter/linter-elixirc/issues/36#issuecomment-170714398).

**Comment by Cifer-Y** [comment] 2016-03-24 07:46
I `mix new` a new project, and write a module as below:
![kv_store ex -users-cifer-dev-exaction-todo atom today at 15 40 50](https://cloud.githubusercontent.com/assets/4470516/14011122/da018d14-f1d6-11e5-81aa-e7b86337c348.png)

then delete the `end` on line 14 and cmd-s to save, then:
![2](https://cloud.githubusercontent.com/assets/4470516/14011150/23a4ce7c-f1d7-11e5-9fa5-5f8aac7353da.png)

**Comment by Arcanemagus** [comment] 2016-03-24 19:47
I'm able to reproduce, looking into it.

**Comment by Arcanemagus** [comment] 2016-03-24 22:14
This is why I was requesting testers for months in #45 :disappointed:

It seems that `elixirc` has completely different output for different error messages, I'll try to come up with a way of solving this...

**Closed** 2016-03-24 23:34 UTC
Labels: bug

**Comment by Arcanemagus** [comment] 2016-03-24 23:37
v1.1.7 is published which should fix this. Please file a new issue if you find another case of this bug, thanks!
