### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by JohnBat26** [AtomLinter/linter-elixirc#57] opened 2016-03-19 09:14 UTC
Hello, When I enable linter-elixirrc I get next error:

~~~
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:493:3)
    at isTestFile (/home/johnbat26/.atom/packages/linter-elixirc/lib/init.coffee:47:27)
    at getDepsPa (/home/johnbat26/.atom/packages/linter-elixirc/lib/init.coffee:107:16)
    at /home/johnbat26/.atom/packages/linter-elixirc/lib/init.coffee:118:7
    at Object.provider.lint (/home/johnbat26/.atom/packages/linter-elixirc/lib/init.coffee:133:11)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/johnbat26/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/johnbat26/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/johnbat26/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/johnbat26/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /home/johnbat26/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1073:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
~~~

**Comment by Arcanemagus** [comment] 2016-03-23 06:29
Looks like this is a duplicate of #53, I'll try to get a fix in in a bit here.

**Closed by Arcanemagus** 2016-03-23 06:29 UTC
Labels: bug

**Comment by jessejanderson** [comment] 2016-06-30 00:50
Running into this same issue.

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at parseError (/Users/Jesse/.atom/packages/linter-elixirc/lib/init.coffee:104:28)
    at /Users/Jesse/.atom/packages/linter-elixirc/lib/init.coffee:130:22

**Comment by Arcanemagus** [comment] 2016-06-30 17:47
@jessejanderson For future reference that should have been filed as a new issue since this is both closed _and_ marked as a duplicate 😛. Found the problem though and cleaning things up now.

**Comment by Arcanemagus** [comment] 2016-06-30 18:19
Please try v1.1.10. If you are still experiencing problems please file a new issue, thanks!

**Comment by jessejanderson** [comment] 2016-06-30 20:44
Whoops, guess I'm not familiar enough with github issue etiquette. 😬 

Thanks! 🎉

**Comment by Arcanemagus** [comment] 2016-06-30 21:02
Not a problem, just a warning that a closed issue is likely to be ignored ("Oh, it's closed, I'll just mark that as read.") so it's best to file a new one, unless a search shows an already open issue.
